version: '3.7'

services:
  #   postgres:
  #     image: postgres:13
  #     container_name: postgres
  #     ports:
  #       - '5432:5432'
  #     environment:
  #       POSTGRES_DB: postgres
  #       POSTGRES_USER: postgres
  #       POSTGRES_PASSWORD: prostoparol
  #     volumes:
  #       - postgres_data:/var/lib/postgresql/data
  # volumes:
  #   postgres_data:

  db:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
